### ISSUE TITLE
unclear Connection URL

### ISSUE THREAD

**Issue by psc-dibuco** [ivangfr/springboot-keycloak-openldap#1]
Hi,
first of all ty for the detailed readme, this is exactly the project i am looking for.

but I need some clarification on the Topic **Configuring Keycloak**

At Point 5. 
> LDAP Integration: On Connection URL type ldap://machine-ip-address.

what exactly did you put in there. I got all your containers running from the docker-compose file. and didnt touch the yml file at all. but if I fill in the Connection URL and hit the **Test connection** button, then nothing happens.

I tried the following URLs:

ldap://localhost:389, ldap://0.0.0.0:389, ldap://ldap-service:389, ldap://127.0.0.1:389, ldap://localhost, ldap://0.0.0.0, ldap://ldap-service, ldap://127.0.0.1 or ldap://localhost 

It works only if I dont use a keycloak docker container but the standalone [keycloak server](https://www.keycloak.org/downloads.html) then i just have to insert ldap://localhost:389 and the click on **Test connection** button results in a "successful" notification.

I think somehow the 2 containers (keycloak and ldap) cant find each other, although they are in the same docker network.

Would be awesome if you could help me on this!

**Comment by ivangfr** [comment]
Hi! You need to provide the ip address of your machine. If your are using Mac or Linux, type on the terminal `ifconfig`. Windows must be `ipconfig`. Let's suppose it is `10.10.10.90`. Then, you set in the field: `ldap://10.10.10.90`.

Or, you can run the following command to get the `ldap-service-docker-ip-address`:
```
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ldap-service
```
Then you add the ip address returned in the field, `ldap://<ldap-service-docker-ip-address>`

Btw, **it seems that it is not working the Keycloak test buttons to check if the LDAP connections is ok (version 4.0.0.Beta1)**.

I also updated the README adding a better explanation about how to get the ldap-service address.

**Comment by psc-dibuco** [comment]
heyho, 

thank you very much. all my errors were caused by using the 4.0.0 beta docker container.

if you want to use the old docker version the environment variables have to be changed:

  postgres:
    image: postgres
    volumes:
        - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
    ports:
        - 5432:5432


  keycloak:
    image: jboss/keycloak:3.4.3.Final # this version needs different env-variables
    hostname: keycloak
    container_name: keycloak
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_DATABASE=keycloak
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT_5432_TCP_ADDR=postgres
      - POSTGRES_PORT_5432_TCP_PORT=5432
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
    ports:
      - 8181:8080
    depends_on:
      - postgres

ty again!
