### ISSUE TITLE
error on phpldapadmin container

### ISSUE THREAD

**Issue by yasahmed** [ivangfr/springboot-keycloak-openldap#4]
i can't get access to phpldapadmin dashboard (192.168.99.100:6443) due to an error on it's container : 

```
Set apache2 https config...
No certificate file and certificate key provided, generate:
/container/service/phpldapadmin/assets/apache2/certs/phpldapadmin.crt and /container/service/phpldapadmin/assets/apache2/certs/phpldapadmin.key
2019/06/11 10:24:22 [INFO] generate received request
2019/06/11 10:24:22 [INFO] received CSR
2019/06/11 10:24:22 [INFO] generating key: ecdsa-384
2019/06/11 10:24:22 [INFO] encoded CSR
2019/06/11 10:24:22 [INFO] signed certificate with serial number 587292907324328512011019972735108992728466332616
Link /container/service/:ssl-tools/assets/default-ca/default-ca.pem to /container/service/phpldapadmin/assets/apache2/certs/ca.crt
Bootstap phpLDAPadmin...
tr: write error: Broken pipe
tr: write error
*** Set environment for container process
*** Remove file /container/environment/99-default/default.startup.yaml
*** Environment files will be proccessed in this order :
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running runit daemon...
[11-Jun-2019 10:24:24] NOTICE: fpm is running, pid 884
[11-Jun-2019 10:24:24] NOTICE: ready to handle connections
[11-Jun-2019 10:24:24] NOTICE: systemd monitor interval set to 10000ms
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.24.0.4. Set the 'ServerName' directive globally to suppress this message
```
is there any required network configuration to do ?

**Comment by ivangfr** [comment]
Hey @yasahmed, this log it ok, at least if you are just running this project locally.

Once the services are UP, just open a browser and access https://localhost:6443

A warning should appear (I am using Chrome), like
```
Your connection is not private
Attackers might be trying to steal your information from localhost (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID
```

Just click on `Advanced` button and then on `Proceed to localhost (unsafe)`

You should see the login page of `phpldapadmin`

**Comment by yasahmed** [comment]
@ivangfr thank's for you'r response but im using docker-machine for windows so docker is configured to use the default machine with IP 192.168.99.100, so there is a probleme, keycloack admin page work fine but  not phpldapadmin page due ti this error : 
`AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.24.0.4. Set the 'ServerName' directive globally to suppress this message`

**Comment by ivangfr** [comment]
@yasahmed I am having the same problem as you
```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.4. Set the 'ServerName' directive globally to suppress this message
```
In spite of that, I can access `phpldapadmin` normally.
How are you trying to open the `phpldapadmin` website?

**Comment by yasahmed** [comment]
Using this link http://192.168.99.100:6443/
http://192.168.99.100:8080 work great for keycloack

**Comment by ivangfr** [comment]
Can you do a print screen of the browser when you try to access http://192.168.99.100:6443?

**Comment by yasahmed** [comment]
![image](https://user-images.githubusercontent.com/6693263/59308846-f8965f00-8c99-11e9-9bf9-b8f41f64a111.png)
sorry it's in french

**Comment by ivangfr** [comment]
@yasahmed I created a docker-machine and I faced the same problem that you are having.

What you are doing wrong is trying to access `http`://192.168.99.100:6443 and not `https`://192.168.99.100:6443

So, try **https**. A different message will appear on the browser. Just follow the instructions I gave you on my first comment about this open issue.

Best regards,

**Comment by yasahmed** [comment]
thank you @ivangfr you are right, it's work fine now :) :)
